# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GfNxlXrFhffWLEoU6lyvGJdTbN8Ay2bd
"""
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
# Load dataset
pokeset = pd.read_csv('res_dpre.csv')

# Data
categories = ['Non-Legendary', 'Legendary']
values = [410.5, 615.3]

# Calculate percentage difference
percent_diff = ((values[1] - values[0]) / values[0]) * 100

# Bar colors (gradient effect)
colors = ["gold", "deepskyblue"]

# Create figure and axes
fig, ax = plt.subplots(figsize=(8, 6), dpi=100)
bars = ax.bar(categories, values, color=colors, edgecolor="white", linewidth=2)

# Add value labels
for bar in bars:
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2, height - 30,
            f"{height:.1f}", ha='center', fontsize=12, fontweight='bold', color="white")

# Add percentage annotation
ax.annotate(f"+{percent_diff:.1f}% stronger!",
            xy=(1, values[1]), xytext=(0.5, (values[0] + values[1]) / 2),
            fontsize=14, color="white", fontweight='bold',
            arrowprops=dict(facecolor='white', arrowstyle="->"))

# Aesthetic improvements
ax.set_facecolor("#222")  # Dark background
fig.patch.set_facecolor("#222")
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.title("Average Base Stats: Legendary vs. Non-Legendary Pokémon", fontsize=14, fontweight='bold', color="white")
plt.xlabel("Pokémon Type", fontsize=12, color="white")
plt.ylabel("Average Base Stats", fontsize=12, color="white")
plt.xticks(color="white")
plt.yticks(color="white")

# Save figure as PNG
plt.savefig("vis.png", bbox_inches="tight", dpi=300, facecolor=fig.get_facecolor())

# Show plot
plt.show()

print("vis.png saved successfully")
os.system("python model.py")